"""empty message

Revision ID: 21081a650835
Revises: 5d86a1cf830d
Create Date: 2023-06-16 14:22:18.871610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21081a650835'
down_revision = '5d86a1cf830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint('email','users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email','users', type_='unique')
    op.drop_column('users','email')
    # ### end Alembic commands ###
